ligo-debugger-extension:
  stage: debugger
  only: [merge_requests, tooling, vscode-production]
  needs: [ print-nix-version ]
  script:
    - nix build $FLAKE_FLAGS 'git+file:///'$PWD'?dir=tools/debugger'#ligo-debugger-extension
    - cp -Lr --no-preserve=mode,ownership,timestamps result/*.vsix ligo-debugger-extension.vsix
  artifacts:
    paths:
      - ligo-debugger-extension.vsix


ligo-debugger-test:
  stage: debugger
  only: [merge_requests, tooling]
  needs: [ print-nix-version, ligo-build ]
  script:
    - git add ./ligo # Ligo binary is needed for this tests
    - nix build $FLAKE_FLAGS 'git+file:///'$PWD'?dir=tools/debugger'#checks.x86_64-linux.ligo-debugger-test

danger-instant-checks:
  stage: validate
  only:
    refs: [merge_requests]
    changes:
      - tools/debugger/**/*
      - danger/**/*
  interruptible: true
  script:
    - nix develop ./tools/debugger#ci -c danger --fail-on-errors=true
        --dangerfile=./danger/instant-checks.rb
        --danger_id=instant

danger-hlint:
  stage: validate
  only:
    refs: [merge_requests]
    changes:
      - tools/debugger/**/*
      - danger/**/*
  interruptible: true
  script:
    - nix develop ./tools/debugger#ci -c danger --fail-on-errors=true
        --dangerfile=./danger/hlint.rb
        --danger_id=hlint

danger-premerge-checks:
  stage: validate-final
  only:
    refs: [merge_requests]
    changes:
      - tools/debugger/**/*
      - danger/**/*
  needs: ["danger-instant-checks"]  # To get messages in MRs ordered right
  when: always
  interruptible: true
  script:
    - nix develop ./tools/debugger#ci -c danger --fail-on-errors=true
        --dangerfile=./danger/premerge-checks.rb
        --danger_id=premerge
  allow_failure: true

# publish vscode extension to the extension marketplace
# copied over from tools/lsp and slightly modified
ligo-debugger-extension-publish:
  stage: push
  needs: [ligo-debugger-extension]
  only: [vscode-production]
  when: manual
  script:
    - nix develop ./tools/vsce --command vsce publish --packagePath *.vsix # uses VSCE_PAT env variable as personal access token
    - nix develop ./tools/vsce --command ovsx publish *.vsix # uses OVSX_PAT env variable as personal access token
